name: Rowdy Deploy Action
description: Deploy a Docker Image with Rowdy
author: Scaffoldly <github.com/scaffoldly>
branding:
  icon: upload-cloud
  color: gray-dark
inputs:
  name:
    description: "The name of the application. (Default: a random name)"
    required: false
    default: ""
  cloud:
    description: "The cloud provider to deploy to (aws, gcp, azure, or digitalocean)"
    required: true
  compute:
    description: "The compute type to deploy to (lambda, ecs, app-engine, azure-functions, or app-platform)"
    required: true
  image:
    description: "The Docker image to deploy (e.g. ghcr.io/owner/repo@sha256:...)"
    required: true
  command:
    description: "Override the ENTRYPOINT/CMD in the Docker image. (Default: ENTRYPOINT+CMD defined in the image"
    required: false
    default: ""
  memory:
    description: "Amount of memory to allocate to the deployed container in megbytes. (Default: 256)"
    required: false
    default: "256"
  cri:
    description: "Enable the Container Runtime Interface (CRI)"
    required: false
    default: "false"
  routes:
    description: "Path to the routes configuration file."
    required: false
    default: ""
outputs:
  url:
    description: The URL of the deployed application.
runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      if: ${{ inputs.cloud == 'aws' }}
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-region: ${{ env.AWS_REGION || 'us-east-1' }}
        role-to-assume: ${{ env.AWS_ROLE_ARN }}

    - name: Set up Node.js
      uses: actions/setup-node@v6

    - name: Deploy with Rowdy
      shell: bash
      run: >
        npx @scaffoldly/rowdy@beta create
        ${{ inputs.cloud }} ${{ inputs.compute }} ${{ inputs.image }}
        ${{ inputs.command }}
      env:
        ROWDY_DEBUG: "true"
        ROWDY_TRACE: "true"
        ROWDY_NAME: "${{ inputs.name }}"
        ROWDY_MEMORY: "${{ inputs.memory }}"
        ROWDY_CRI: "${{ inputs.cri }}"
        ROWDY_ROUTES: "${{ inputs.routes }}"
