#!/usr/bin/env node
// Embeds the compiled shims (lib/linux-<arch>/vfspreload.so) into src/shims.ts
// as base64 so the package is a single JS artifact: no native postinstall, and
// `pkg`-built consumers carry the shim inside their snapshot.
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const archs = ['x64', 'arm64'];
const out = path.join(root, 'src', 'shims.ts');

const entries = archs.map((arch) => {
  const file = path.join(root, 'lib', `linux-${arch}`, 'vfspreload.so');
  if (!fs.existsSync(file)) {
    console.warn(`embed: missing ${path.relative(root, file)} (run \`yarn build:native\`); embedding nothing for ${arch}`);
    return `  'linux-${arch}': undefined,`;
  }
  const data = fs.readFileSync(file);
  if (data.subarray(0, 4).toString('latin1') !== '\x7fELF') {
    throw new Error(`embed: ${file} is not an ELF object`);
  }
  console.log(`embed: linux-${arch} ${data.length} bytes`);
  return `  'linux-${arch}': '${data.toString('base64')}',`;
});

fs.writeFileSync(
  out,
  [
    '// GENERATED by scripts/embed.js from lib/linux-<arch>/vfspreload.so. Do not edit.',
    '/* eslint-disable */',
    'export const shims: Record<string, string | undefined> = {',
    ...entries,
    '};',
    '',
  ].join('\n')
);
